config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  root to: "flats#home"
  # Defines the root path route ("/")
  # root "posts#index"
  resources :flats 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update]

  def home
  end
  def index
    if params[:query].present?
      @flats = Flat.where("name LIKE ?","%#{params[:query]}%")
    else
      @flats = Flat.all
    end
  end

  def show
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
      if @flat.save
        redirect_to flats_path
      else
      render :new, status: :unprocessable_entity
      end
  end

  def edit
  end

  def update
    if @flat.update(flat_params)
      redirect_to flat_path(@flat), notice: "update with success!"
    else
      render :edit, status: :unprocessable_entity
    end
  end

    def destroy
      @flat = Flat.find(params[:id])
      @flat.destroy
      redirect_to flat_path(@flat), status: :see_other
    end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:picture_url, :name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<div class="form">
  <div class="form-content">
    <%= simple_form_for(@flat) do |f| %>
    <%= f.input :picture_url, class: "form-control" %>
    <%= f.input :name %>
    <%= f.input :address, input_html: { autocomplete: "off", "aria-autocomplete" => "none", "data-password" => "false"} %>
    <%= f.input :description %>
    <%= f.input :price_per_night %>
    <%= f.input :number_of_guests %>
    <%= f.submit "Create", class:'btn btn-primary' %>
    <%= link_to "Cancel", flats_path, class:'btn btn-danger' %>

    <% end %>
  </div>
</div>

app/views/flats/edit.html.erb
  <h1 class="text-center">Edit a Flat</h1>
<%= render 'form', flat: @flat%>

app/views/flats/home.html.erb
<div class="text-center">
    <%= link_to "Par ici", flats_path%>
</div>

app/views/flats/index.html.erb
<div class="container my-3">
 <h1 class="mb-3"> <%= link_to "All our Flats (#{ Flat.count })", flats_path, class:"text-decoration-none text-dark" %></h1>
  <div class="row">
    <% @flats.each do |flat| %>
      <div class="col-md-4 ps-3">
        <div class="card mb-4 shadow-sm">
          <div class="card-body px-3">
            <div class="card-body-main">
              <div class="picture">
                <img src="<%= flat.picture_url %>" style="width: 100%; height: auto;">
              </div>
              <div class="title">
              <strong><%= flat.name %></strong>
              </div>
                <div class="description mt-2">
                  <%= flat.description %>
                  <%= flat.address %>
                  </div>
                    <div class="details mt-2">
                      <div class="number me-3"><i class="fa-solid fa-users me-2"></i><%= flat.number_of_guests %></div>
                      <div class="price"><i class="fa-solid fa-euro-sign me-2"></i><%= flat.price_per_night %></div>
                    </div>
              </div>
              </div>
              <div id="card-body-link">
                  <div class="more p-3">
                    <%= link_to "More", flat_path(flat), class:"me-2" %>
                    <%= link_to "Edit", edit_flat_path(flat), class:"me-2 link-warning" %>
                    <%= link_to "Remove", flat_path(flat), class:"text-danger", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
                  </div>
                </div>


          </div>

      </div>
       <% end %>
  </div>
</div>

app/views/flats/new.html.erb
  <h1 class="text-center">Add a new Flat</h1>
<%= render 'form' %>

app/views/flats/show.html.erb
<div class="picture">
  <img src="<%= @flat.picture_url %>">
</div>
<div class="relative">
<div class="show">
  <div class="card-container">
          <div class="card-flat">
            <strong><h2><%= @flat.name %></h2></strong>
            <%= @flat.address %>
          </div>

          <div class="card-flat">
            <h4>A bit more about this flat...</h4>
            <%= @flat.description %>
          </div>

          <div class="card-flat">
            <h4>Details</h3>
              <i class="fa-solid fa-users me-2"></i><%= @flat.number_of_guests %>
              <i class="fa-solid fa-euro-sign me-2"></i><%= @flat.price_per_night %>
          </div>
  </div>

  <div class="book">
    <div class="book-form">
       <h5>Book this place !</h5>
      <div class="mb-3">
          <label for="formFileMultiple" class="form-label"></label>
          <input text="to"class="form-control" type="file" id="formFileMultiple" multiple>
      </div>
        <div class="mb-3">
          <label for="formFileMultiple" class="form-label"></label>
          <input class="form-control" type="file" id="formFileMultiple" multiple>
        </div>
        <div class="button">
          <a class="btn" href="#">Book now</a>
        </div>
    </div>
    <div class="link-rs px-4">
      <div class="fs-5">Share</div>
      <div class="rs fs-4">
        <i class="fa-brands fa-square-facebook"></i>
        <i class="fa-brands fa-square-twitter"></i>
        <i class="fa-brands fa-square-pinterest"></i>
        <i class="fa-solid fa-envelope"></i>
      </div>
    </div>


  </div>

</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="navbar .text-dark">
      <strong><%= link_to "Simple Airbnb", flats_path, class:"pt-1 text-decoration-none text-body" %></strong>
      <div class="d-flex justify-content-end">
        <div class="search">
          <%= form_with url: flats_path, method: :get, local: true do %>
          <%= text_field_tag :query, params[:query], placeholder: "search a flat...", class:"rounded"%>
          <%= submit_tag "search", class:"btn btn-outline-success me-2"%>
          <% end %>
        </div>
        <div>
          <%= link_to "Add Flat", new_flat_path, class:"btn btn-outline-primary"%>
        </div>
      </div>
      </div>
    <div class="container mt-3">
        <%= yield %>
    </div>
  </body>
</html>